{{- if .Values.hpa.enabled -}}
# @formatter:off
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "video-online-back.fullname" . }}
  labels:
{{ include "video-online-back.labels" . | indent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "video-online-back.fullname" . }}
  minReplicas: {{ .Values.hpa.minReplicas | default .Values.replicaCount }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
    {{- if .Values.hpa.custom }}
    - type: Object
      object:
        metric:
          name: {{ .Values.hpa.custom.metricName }}
        describedObject:
          apiVersion: {{ include "video-online-back.ingress.apiVersion" . }}
          kind: {{ .Values.hpa.custom.objectKind }}
          name: {{ .Values.hpa.custom.objectName }}
        target:
          type: Value
          value: {{ .Values.hpa.custom.targetValue }}
    {{- end }}
    {{- if .Values.hpa.cpu }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.cpu }}
    {{- end }}
    {{- if .Values.hpa.memory }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.memory }}
    {{- end }}
{{- end }}
